### ISSUE TITLE
Getting "dirname" errors 

### ISSUE THREAD

**Issue by quickredfox** [kriskowal/lode#1]
Hey Kris. You sent me a tweet a coupla days ago to come and check lode out... And I'm doing so now:)

 I know it's hot off the plates and you're probably busy enough as it is but if you could shed some light on a few things, I cant seem to get things working (which surprises me because so far all your code has been a breeze to install ). 

So I have hacked-up a package.json file like this: 

```
         {
          "lode": true,
          "name": "produce",
          "description": "Top secret because I have no clue",
          "version": "0.0.1",
          "author": "Francois Lafortune (http://about.me/quickredfox)",
          "mappings": {
            "q": "mappings/q"
          },
          "directories":{
             "lib": "./lib",
             "src": "./src"     
          },
          "main": "produce.js",
          "supportDefine": true
        }
```

I've got my usual /lib (compiled .js) /src (coffeescript) folders setup and some minimal code that prints out a "hello world". 

My problem is that whenever I try to run the lode executable, there seems to be some inconsistencies with lode's q-fs dependencies. I always get a 

```
TypeError: Object #<Object> has no method 'dirname' at NoPackage 
```

Comming from line 160 of lode.js

**Comment by quickredfox** [comment]
Uh hum.... I've played around with the code a bit and I came to the conclusion that my request is probably quite premature. Well at least it goes to show how much faith I have in this project... So it's up to you to decide if above issue is valid or not (I'm closing it).
But I'm seeing what I presume is a lot of missing/unfinished stuff as I try to work around issues so maybe I'm just too quick on the git cloning? 

Keep up the great work BTW.

**Comment by kriskowal** [comment]
Yeah, the project is still in its infancy. I just finished support for archived and web hosted packages, but I only support Lode packages at the moment, which is highly restrictive (so, your "mappings/q" won't work quite yet because "q" is an NPM package, not a Lode package). I intend to re-integrate the feature that detects what type of package each package is and attempt to coerce it into Lodese, and I already support a stopgap {"system": id} dependency style in `master` for grandfathering in system-installed packages.

This particular exception might actually be a bug, probably with the q-fs dependency. I rewrote that module over the last week, so I probably won't be able to reproduce it. In any case, thanks for trying it out. I had intended that you might just read the README to get an idea of where this is going, but your enthusiasm is strongly appreciated.

**Comment by quickredfox** [comment]
Now that you point it out, mappings/q not working is quite obvious, it's even implied in the README. So anyways, I'm pretty much OK with just using q-require for now, a bit less of a hassle than teleport for my current needs. 

As for just reading the README well, let me just say you have such a talent for them (love the "This is cool" bits) that I can't help but to try and dive in. Seriously, I'm using Q in some projects instead of jQuery 1.5's $.Deferred() just because I can :)
